#!/bin/sh
set -eu

REPOSITORY="terno-projects/terno"
INSTALL_DIR="${HOME:?HOME must be set}/.local/bin"
INSTALL_PATH="${INSTALL_DIR}/terno"
SERVER_URL="${TERNO_SERVER:?run the installation command generated by Terno}"
unset TERNO_SERVER
HOST_OS="$(uname -s)"
temporary_dir=""
staged_binary=""

fail() { printf 'error: %s\n' "$*" >&2; exit 1; }
say() { printf '%s\n' "$*"; }
require() { command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"; }
cleanup() {
  [ -z "${temporary_dir}" ] || rm -rf -- "${temporary_dir}"
  [ -z "${staged_binary}" ] || rm -f -- "${staged_binary}"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM HUP

[ "$#" -eq 1 ] || fail 'run the complete installation command generated by Terno'
ENROLL_SECRET="$1"
shift
[ "${#ENROLL_SECRET}" -eq 43 ] || fail 'invalid Agent installation secret'
case "$ENROLL_SECRET" in *[!A-Za-z0-9_-]*) fail 'invalid Agent installation secret' ;; esac
case "$SERVER_URL" in https://*) ;; *) fail 'invalid Terno server address' ;; esac
case "$INSTALL_DIR" in /*) ;; *) fail 'install path must be an absolute path' ;; esac
case "$INSTALL_DIR" in *'
'*) fail 'install path cannot contain a newline' ;; esac
case "$(uname -m)" in x86_64|amd64) target_arch=amd64 ;; aarch64|arm64) target_arch=arm64 ;; *) fail 'only amd64 and arm64 are supported' ;; esac
for tool in curl jq mktemp chmod sed id; do require "$tool"; done
case "$HOST_OS" in
  Linux)
    target_os=linux
    checksum_tool=sha256sum
    require sha256sum
    require systemctl
    DATA_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/terno-agent"
    if [ "$(id -u)" -eq 0 ]; then
      SERVICE_FILE=/etc/systemd/system/terno-agent.service
      SERVICE_TARGET=multi-user.target
      SERVICE_SCOPE=system
      systemctl --system show-environment >/dev/null 2>&1 || fail 'systemd system manager unavailable'
    else
      SERVICE_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user/terno-agent.service"
      SERVICE_TARGET=default.target
      SERVICE_SCOPE=user
      systemctl --user show-environment >/dev/null 2>&1 || fail 'systemd user manager unavailable; log in as this user with a systemd session'
    fi
    ;;
  Darwin)
    target_os=darwin
    checksum_tool=shasum
    require shasum
    require launchctl
    require plutil
    DATA_DIR="$HOME/Library/Application Support/terno-agent"
    SERVICE_LABEL=projects.terno.agent
    if [ "$(id -u)" -eq 0 ]; then
      SERVICE_FILE="/Library/LaunchDaemons/${SERVICE_LABEL}.plist"
      LAUNCH_DOMAIN=system
      LOG_DIR=/Library/Logs/TernoAgent
    else
      SERVICE_FILE="$HOME/Library/LaunchAgents/${SERVICE_LABEL}.plist"
      LAUNCH_DOMAIN="gui/$(id -u)"
      LOG_DIR="$HOME/Library/Logs/TernoAgent"
    fi
    launchctl print "$LAUNCH_DOMAIN" >/dev/null 2>&1 || fail 'launchd domain unavailable; install from a GUI login session, or as root for a system daemon'
    ;;
  *) fail "unsupported operating system: $HOST_OS" ;;
esac
service_control() { systemctl "--${SERVICE_SCOPE}" "$@"; }
systemd_escape() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/%/%%/g'; }
xml_escape() { printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'; }

if [ -e "$INSTALL_PATH" ] || [ -L "$INSTALL_PATH" ]; then
  [ ! -L "$INSTALL_PATH" ] || fail 'refusing to replace a symbolic link'
  [ -x "$INSTALL_PATH" ] || fail 'existing install path is not executable'
  case "$("$INSTALL_PATH" --version 2>/dev/null)" in 'terno '*) ;; *) fail 'existing file does not identify itself as Terno' ;; esac
fi

temporary_dir="$(mktemp -d "${TMPDIR:-/tmp}/terno-agent-install.XXXXXX")"
curl --proto '=https' --tlsv1.2 -fsSL --retry 3 --connect-timeout 15 --max-time 90 \
  -H 'Accept: application/vnd.github+json' "https://api.github.com/repos/${REPOSITORY}/releases/latest" -o "${temporary_dir}/release.json"
release_tag="$(jq -er '.tag_name | select(test("^v[0-9]+\\.[0-9]+\\.[0-9]+$"))' "${temporary_dir}/release.json")" || fail 'invalid release tag'
asset_name="terno-${release_tag}-${target_os}-${target_arch}"
expected_checksum="$(jq -er --arg name "$asset_name" '[.assets[] | select(.name == $name)] | select(length == 1) | .[0].digest | select(test("^sha256:[0-9a-fA-F]{64}$")) | sub("^sha256:"; "") | ascii_downcase' "${temporary_dir}/release.json")" || fail 'release has no unique Terno asset with a SHA256 digest'
say "Downloading Terno ${release_tag} for ${target_os}/${target_arch}..."
curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL --retry 3 --connect-timeout 15 --max-time 300 \
  "https://github.com/${REPOSITORY}/releases/download/${release_tag}/${asset_name}" -o "${temporary_dir}/terno"
if [ "$checksum_tool" = sha256sum ]; then actual_checksum="$(sha256sum "${temporary_dir}/terno")"
else actual_checksum="$(shasum -a 256 "${temporary_dir}/terno")"; fi
actual_checksum="${actual_checksum%% *}"
[ "$actual_checksum" = "$expected_checksum" ] || fail 'SHA256 mismatch; installation was not changed'
chmod 0755 "${temporary_dir}/terno"
[ "$("${temporary_dir}/terno" --version)" = "terno ${release_tag#v}" ] || fail 'downloaded Terno failed version verification'

printf '%s' "$ENROLL_SECRET" | "${temporary_dir}/terno" agent --enroll-stdin --prepare --data-dir "$DATA_DIR"
mkdir -p "$INSTALL_DIR" "$(dirname "$SERVICE_FILE")"
staged_binary="$(mktemp "${INSTALL_DIR}/.terno-install.XXXXXX")"
cp "${temporary_dir}/terno" "$staged_binary"
chmod 0755 "$staged_binary"
if [ "$HOST_OS" = Darwin ] && launchctl print "$LAUNCH_DOMAIN/$SERVICE_LABEL" >/dev/null 2>&1; then
  launchctl bootout "$LAUNCH_DOMAIN/$SERVICE_LABEL"
fi
mv -f -- "$staged_binary" "$INSTALL_PATH"
staged_binary=""
if [ "$HOST_OS" = Linux ]; then
  cat > "$SERVICE_FILE" <<UNIT
[Unit]
Description=Terno Agent
After=network-online.target

[Service]
Type=simple
Environment="HOME=$(systemd_escape "$HOME")"
Environment="XDG_CONFIG_HOME=$(systemd_escape "${XDG_CONFIG_HOME:-$HOME/.config}")"
ExecStart="$(systemd_escape "$INSTALL_PATH")" agent --server "$(systemd_escape "$SERVER_URL")" --data-dir "$(systemd_escape "$DATA_DIR")"
Restart=on-failure
RestartSec=5

[Install]
WantedBy=${SERVICE_TARGET}
UNIT
  service_control daemon-reload
  service_control enable terno-agent.service
  service_control restart terno-agent.service
else
  mkdir -p "$LOG_DIR"
  cat > "$SERVICE_FILE" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>Label</key><string>${SERVICE_LABEL}</string>
<key>ProgramArguments</key><array><string>$(xml_escape "$INSTALL_PATH")</string><string>agent</string><string>--server</string><string>$(xml_escape "$SERVER_URL")</string><string>--data-dir</string><string>$(xml_escape "$DATA_DIR")</string></array>
<key>EnvironmentVariables</key><dict><key>HOME</key><string>$(xml_escape "$HOME")</string><key>PATH</key><string>$(xml_escape "$PATH")</string></dict>
<key>RunAtLoad</key><true/>
<key>KeepAlive</key><true/>
<key>StandardOutPath</key><string>$(xml_escape "$LOG_DIR")/agent.log</string>
<key>StandardErrorPath</key><string>$(xml_escape "$LOG_DIR")/agent-error.log</string>
<key>ThrottleInterval</key><integer>5</integer>
</dict></plist>
PLIST
  chmod 0644 "$SERVICE_FILE"
  plutil -lint "$SERVICE_FILE"
  launchctl enable "$LAUNCH_DOMAIN/$SERVICE_LABEL"
  launchctl bootstrap "$LAUNCH_DOMAIN" "$SERVICE_FILE"
fi
sleep 2
if [ "$HOST_OS" = Linux ]; then
  service_control is-active --quiet terno-agent.service || fail 'Agent service did not start; inspect its service logs'
else
  launchctl print "$LAUNCH_DOMAIN/$SERVICE_LABEL" | awk '/state = running/ { running = 1 } END { exit !running }' || fail "Agent did not start; inspect logs in $LOG_DIR"
fi
say "Terno Agent ${release_tag} is running and connecting to Terno over HTTPS."
say 'Return to Terno; the host becomes ready when the connection is established.'
