[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$EnrollSecret,
    [string]$ServerUrl = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
if ($env:OS -ne 'Windows_NT') { throw 'This installer supports Windows only.' }
$windowsVersion = [Environment]::OSVersion.Version
if ($windowsVersion.Major -lt 10 -or $windowsVersion.Build -lt 17763) {
    throw 'Terno Agent requires Windows 10 version 1809 / Windows Server 2019 or later.'
}
if ($EnrollSecret -cnotmatch '^[A-Za-z0-9_-]{43}$') { throw 'Invalid Agent installation secret.' }
$parsedServer = $null
if (-not [Uri]::TryCreate($ServerUrl, [UriKind]::Absolute, [ref]$parsedServer) -or $parsedServer.Scheme -ne 'https') {
    throw 'Run the complete installation command generated by Terno.'
}

$Repository = 'terno-projects/terno'
$InstallDirectory = Join-Path ([Environment]::GetFolderPath('LocalApplicationData')) 'Programs\Terno Agent\bin'
$InstallPath = Join-Path $InstallDirectory 'terno.exe'
$AgentDataDirectory = Join-Path ([Environment]::GetFolderPath('ApplicationData')) 'terno-agent'
$LogDirectory = Join-Path ([Environment]::GetFolderPath('LocalApplicationData')) 'TernoAgent\logs'
$RunnerPath = Join-Path $InstallDirectory 'run-agent.ps1'
$PowerShellPath = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
$StartupDirectory = [Environment]::GetFolderPath('Startup')
$StartupShortcutPath = Join-Path $StartupDirectory 'Terno Agent.lnk'
$escapedRunnerPath = $RunnerPath.Replace("'", "''")
$EncodedRunner = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes("& '$escapedRunnerPath'"))
$RunnerArguments = "-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -EncodedCommand $EncodedRunner"

function Get-AgentProcesses {
    @(Get-Process -Name 'terno' -ErrorAction SilentlyContinue | Where-Object {
        [StringComparer]::OrdinalIgnoreCase.Equals($_.Path, $InstallPath)
    })
}

if (Test-Path -LiteralPath $InstallPath) {
    if ((Get-Item -LiteralPath $InstallPath).Attributes -band [IO.FileAttributes]::ReparsePoint) {
        throw 'Refusing to replace a symbolic link.'
    }
    $identity = (& $InstallPath --version | Out-String).Trim()
    if ($LASTEXITCODE -ne 0 -or $identity -notmatch '^terno\s+') { throw 'Existing file does not identify itself as Terno.' }
}

$machineArchitecture = if ($env:PROCESSOR_ARCHITEW6432) { $env:PROCESSOR_ARCHITEW6432 } else { $env:PROCESSOR_ARCHITECTURE }
$TargetArchitecture = switch ($machineArchitecture.ToUpperInvariant()) {
    'AMD64' { 'amd64' }
    'ARM64' { 'arm64' }
    default { throw "Unsupported Windows architecture: $machineArchitecture" }
}
$headers = @{ Accept = 'application/vnd.github+json'; 'X-GitHub-Api-Version' = '2022-11-28' }
$release = Invoke-RestMethod -Uri "https://api.github.com/repos/$Repository/releases/latest" -Headers $headers -UserAgent 'Terno-Agent-Installer' -UseBasicParsing
$ReleaseTag = [string]$release.tag_name
if ($ReleaseTag -notmatch '^v[0-9]+\.[0-9]+\.[0-9]+$') { throw 'Could not determine the latest release.' }
$AssetName = "terno-$ReleaseTag-windows-$TargetArchitecture.exe"
$assets = @($release.assets | Where-Object { $_.name -eq $AssetName })
if ($assets.Count -ne 1) { throw "Release $ReleaseTag does not contain a unique $AssetName." }
$asset = $assets[0]
if ([string]$asset.digest -notmatch '^sha256:([0-9a-fA-F]{64})$') { throw 'Release asset has no valid SHA-256 digest.' }
$ExpectedChecksum = $Matches[1].ToLowerInvariant()
$TemporaryDirectory = Join-Path ([IO.Path]::GetTempPath()) ('terno-agent-install-' + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $TemporaryDirectory | Out-Null
try {
    $DownloadedBinary = Join-Path $TemporaryDirectory 'terno.exe'
    Invoke-WebRequest -Uri ([string]$asset.browser_download_url) -OutFile $DownloadedBinary -UserAgent 'Terno-Agent-Installer' -UseBasicParsing
    $checksum = (Get-FileHash -LiteralPath $DownloadedBinary -Algorithm SHA256).Hash.ToLowerInvariant()
    if ($checksum -ne $ExpectedChecksum) { throw 'SHA-256 mismatch; installation was not changed.' }
    $identity = (& $DownloadedBinary --version | Out-String).Trim()
    if ($LASTEXITCODE -ne 0 -or $identity -ne "terno $($ReleaseTag.Substring(1))") { throw 'Downloaded binary failed version verification.' }
    $EnrollSecret | & $DownloadedBinary agent --enroll-stdin --prepare --data-dir $AgentDataDirectory
    if ($LASTEXITCODE -ne 0) { throw 'Could not initialize Agent credentials.' }

    # Stop the managed runner before the Agent, so it cannot restart during replacement.
    $runners = @(Get-CimInstance Win32_Process -Filter "Name = 'powershell.exe'" | Where-Object {
        [StringComparer]::OrdinalIgnoreCase.Equals($_.ExecutablePath, $PowerShellPath) -and
        $_.CommandLine -and $_.CommandLine.Contains($EncodedRunner)
    })
    foreach ($runner in $runners) {
        Stop-Process -Id $runner.ProcessId
        Wait-Process -Id $runner.ProcessId -Timeout 15 -ErrorAction SilentlyContinue
        if (Get-Process -Id $runner.ProcessId -ErrorAction SilentlyContinue) { throw 'Could not stop the existing Agent runner.' }
    }
    foreach ($agentProcess in @(Get-AgentProcesses)) {
        Stop-Process -Id $agentProcess.Id
        Wait-Process -Id $agentProcess.Id -Timeout 15 -ErrorAction SilentlyContinue
        if (Get-Process -Id $agentProcess.Id -ErrorAction SilentlyContinue) { throw 'Could not stop the existing Agent.' }
    }
    New-Item -ItemType Directory -Path $InstallDirectory -Force | Out-Null
    New-Item -ItemType Directory -Path $LogDirectory -Force | Out-Null
    Copy-Item -LiteralPath $DownloadedBinary -Destination $InstallPath -Force
    $escapedBinary = $InstallPath.Replace("'", "''")
    $escapedLog = (Join-Path $LogDirectory 'agent.log').Replace("'", "''")
    $escapedErrorLog = (Join-Path $LogDirectory 'agent-error.log').Replace("'", "''")
    $agentArguments = ('agent --server "' + $ServerUrl + '" --data-dir "' + $AgentDataDirectory + '"').Replace("'", "''")
    $runnerScript = @"
`$ErrorActionPreference = 'Stop'
while (`$true) {
    Start-Process -FilePath '$escapedBinary' -ArgumentList '$agentArguments' -WindowStyle Hidden -Wait -RedirectStandardOutput '$escapedLog' -RedirectStandardError '$escapedErrorLog'
    Start-Sleep -Seconds 5
}
"@
    Set-Content -LiteralPath $RunnerPath -Value $runnerScript -Encoding UTF8
    # A Startup shortcut supports long command lines and needs no administrator access.
    New-Item -ItemType Directory -Path $StartupDirectory -Force | Out-Null
    $shortcutShell = New-Object -ComObject WScript.Shell
    $shortcut = $shortcutShell.CreateShortcut($StartupShortcutPath)
    $shortcut.TargetPath = $PowerShellPath
    $shortcut.Arguments = $RunnerArguments
    $shortcut.WorkingDirectory = $InstallDirectory
    $shortcut.WindowStyle = 7
    $shortcut.Save()
    $runnerProcess = Start-Process -FilePath $PowerShellPath -ArgumentList $RunnerArguments -WindowStyle Hidden -PassThru
    $started = $false
    for ($attempt = 0; $attempt -lt 30; $attempt++) {
        Start-Sleep -Seconds 1
        if ($runnerProcess.HasExited) { throw "Agent runner exited; inspect logs in $LogDirectory." }
        if (@(Get-AgentProcesses).Count -gt 0) { $started = $true; break }
    }
    if (-not $started) { throw "Agent did not start; inspect logs in $LogDirectory." }
    Write-Host "Terno Agent $ReleaseTag is running. It will start automatically when this user signs in."
    Write-Host 'Return to Terno; the host becomes ready when the connection is established.'
}
finally {
    Remove-Item -LiteralPath $TemporaryDirectory -Recurse -Force
}
