#!/bin/sh
set -eu

REPOSITORY="terno-projects/terno"
INSTALL_DIR="${HOME:?HOME must be set}/.local/bin"
INSTALL_PATH="${INSTALL_DIR}/terno-agent"
SERVER_URL="${TERNO_SERVER:?run the installation command generated by Terno}"
unset TERNO_SERVER
temporary_dir=""
staged_binary=""

fail() { printf 'error: %s\n' "$*" >&2; exit 1; }
say() { printf '%s\n' "$*"; }
require() { command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"; }
cleanup() {
  [ -z "${temporary_dir}" ] || rm -rf -- "${temporary_dir}"
  [ -z "${staged_binary}" ] || rm -f -- "${staged_binary}"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM HUP

[ "$#" -eq 1 ] || fail 'run the complete installation command generated by Terno'
ENROLL_SECRET="$1"
shift
[ "${#ENROLL_SECRET}" -eq 43 ] || fail 'invalid Agent installation secret'
case "$ENROLL_SECRET" in *[!A-Za-z0-9_-]*) fail 'invalid Agent installation secret' ;; esac
case "$SERVER_URL" in https://*) ;; *) fail 'invalid Terno server address' ;; esac
case "$INSTALL_DIR" in /*) ;; *) fail 'install path must be an absolute path' ;; esac
case "$INSTALL_DIR" in *'
'*) fail 'install path cannot contain a newline' ;; esac
[ "$(uname -s)" = Linux ] || fail 'Terno Agent currently supports Linux only'
case "$(uname -m)" in x86_64|amd64) target_arch=amd64 ;; aarch64|arm64) target_arch=arm64 ;; *) fail 'only amd64 and arm64 are supported' ;; esac
for tool in curl jq mktemp chmod sed systemctl sha256sum id; do require "$tool"; done
if [ "$(id -u)" -eq 0 ]; then
  SERVICE_FILE=/etc/systemd/system/terno-agent.service
  SERVICE_TARGET=multi-user.target
  SERVICE_SCOPE=system
  systemctl --system show-environment >/dev/null 2>&1 || fail 'systemd system manager unavailable'
else
  SERVICE_FILE="${XDG_CONFIG_HOME:-${HOME}/.config}/systemd/user/terno-agent.service"
  SERVICE_TARGET=default.target
  SERVICE_SCOPE=user
  systemctl --user show-environment >/dev/null 2>&1 || fail 'systemd user manager unavailable; log in as this user with a systemd session'
fi
service_control() { systemctl "--${SERVICE_SCOPE}" "$@"; }

if [ -e "$INSTALL_PATH" ] || [ -L "$INSTALL_PATH" ]; then
  [ ! -L "$INSTALL_PATH" ] || fail 'refusing to replace a symbolic link'
  [ -x "$INSTALL_PATH" ] || fail 'existing install path is not executable'
  case "$("$INSTALL_PATH" --version 2>/dev/null)" in 'terno-agent '*) ;; *) fail 'existing file does not identify itself as Terno Agent' ;; esac
fi

temporary_dir="$(mktemp -d "${TMPDIR:-/tmp}/terno-agent-install.XXXXXX")"
curl --proto '=https' --tlsv1.2 -fsSL --retry 3 --connect-timeout 15 --max-time 90 \
  -H 'Accept: application/vnd.github+json' "https://api.github.com/repos/${REPOSITORY}/releases/latest" -o "${temporary_dir}/release.json"
release_tag="$(jq -er '.tag_name | select(test("^v[0-9]+\\.[0-9]+\\.[0-9]+$"))' "${temporary_dir}/release.json")" || fail 'invalid release tag'
asset_name="terno-agent-${release_tag}-linux-${target_arch}"
expected_checksum="$(jq -er --arg name "$asset_name" '[.assets[] | select(.name == $name)] | select(length == 1) | .[0].digest | select(test("^sha256:[0-9a-fA-F]{64}$")) | sub("^sha256:"; "") | ascii_downcase' "${temporary_dir}/release.json")" || fail 'release has no unique Agent asset with a SHA256 digest'
say "Downloading Terno Agent ${release_tag} for linux/${target_arch}..."
curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL --retry 3 --connect-timeout 15 --max-time 300 \
  "https://github.com/${REPOSITORY}/releases/download/${release_tag}/${asset_name}" -o "${temporary_dir}/terno-agent"
actual_checksum="$(sha256sum "${temporary_dir}/terno-agent")"
actual_checksum="${actual_checksum%% *}"
[ "$actual_checksum" = "$expected_checksum" ] || fail 'SHA256 mismatch; installation was not changed'
chmod 0755 "${temporary_dir}/terno-agent"
[ "$("${temporary_dir}/terno-agent" --version)" = "terno-agent ${release_tag#v}" ] || fail 'downloaded Agent failed version verification'

printf '%s' "$ENROLL_SECRET" | "${temporary_dir}/terno-agent" --enroll-stdin --prepare
mkdir -p "$INSTALL_DIR" "$(dirname "$SERVICE_FILE")"
staged_binary="$(mktemp "${INSTALL_DIR}/.terno-agent-install.XXXXXX")"
cp "${temporary_dir}/terno-agent" "$staged_binary"
chmod 0755 "$staged_binary"
mv -f -- "$staged_binary" "$INSTALL_PATH"
staged_binary=""
systemd_escape() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/%/%%/g'; }
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Terno Agent
After=network-online.target

[Service]
Type=simple
Environment="HOME=$(systemd_escape "$HOME")"
Environment="XDG_CONFIG_HOME=$(systemd_escape "${XDG_CONFIG_HOME:-$HOME/.config}")"
ExecStart="$(systemd_escape "$INSTALL_PATH")" --server "$(systemd_escape "$SERVER_URL")"
Restart=on-failure
RestartSec=5

[Install]
WantedBy=${SERVICE_TARGET}
EOF
service_control daemon-reload
service_control enable terno-agent.service
service_control restart terno-agent.service
sleep 2
service_control is-active --quiet terno-agent.service || fail 'Agent service did not start; inspect its service logs'
say "Terno Agent ${release_tag} is running and connecting to Terno over HTTPS."
say 'Return to Terno; the host becomes ready when the connection is established.'
